siteName: websiterabia
productionUrl: https://poko-1b6.pages.dev/
languages:
  - code: fr
    name: fran√ßais
    customUrlPrefix: null
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
